server:
  port: 9291
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: supermarket
  username: root
  password: root
  charset: utf8
  loc: Asia/Shanghai
redis:
  host: 127.0.0.1
  database: 0
  port: 6379